### ISSUE TITLE
Display US cities & State? 

### ISSUE THREAD

**Issue by copypasteho** [zhem4ag/jquery_cityAutocomplete#1]
Love this plugin! Is there a way to display the state name for the United States (e.g, Boston, MD; Miami, FL) ? As it stands right now only city names (e.g. Boston, Miami) are auto suggested and auto completed. I tried messing with your code but no luck... Thanks!

**Comment by e-vyatkin** [comment]
Updated version to 1.4.0.
Added options to show state and country in dropdown.
